llm:
  provider: ${HYALINE_LLM_PROVIDER}
  model: ${HYALINE_LLM_MODEL}
  key: ${HYALINE_LLM_TOKEN}


github:
  token: ${HYALINE_GITHUB_TOKEN}


extract:
  source:
    id: hyaline-github-app-config
    description: Documentation for Repository appgardenstudios/hyaline-github-app-config
  crawler:
    type: git
    options:
      repo: https://github.com/appgardenstudios/hyaline-github-app-config.git
      branch: main
      clone: true
      auth:
        type: http
        options:
          username: git
          password: ${HYALINE_GITHUB_TOKEN}
    include:
      - "**/*.md"
    exclude:
      - ".github/**/*"
  extractors:
    - type: md
      include:
        - "**/*.md"



