name = "hyaline-github-app"
compatibility_date = "2025-08-20"
main = "src/index.js"

[[routes]]
pattern = "github-app.hyaline.dev"
custom_domain = true

[observability]
enabled = true

# These should be set as secrets in Cloudflare dashboard
# GITHUB_APP_ID = "your-app-id"
# GITHUB_PRIVATE_KEY = "your-private-key-pem-content"
# WEBHOOK_SECRET = "your-webhook-secret"