name: Internal - Audit

on:
  workflow_dispatch:
    inputs:
      audit:
        description: 'Audit Name'
        type: string
      repo:
        description: 'Repository Name'
        type: string
      site:
        description: 'Site Name'
        type: string
      config:
        description: 'Configuration Path'
        type: string
      sources:
        description: 'Sources (Comma Separated)'
        type: string

permissions: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}
      - name: Setup Hyaline CLI
        uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Audit
        uses: ./.github/actions/_audit
        with:
          audit: ${{ inputs.audit }}
          repo: ${{ inputs.repo }}
          site: ${{ inputs.site }}
          config: ${{ inputs.config }}
          sources: ${{ inputs.sources }}
        env:
          HYALINE_GITHUB_TOKEN: ${{ secrets.HYALINE_GITHUB_TOKEN }}
          HYALINE_CONFIG_GITHUB_TOKEN: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}
          HYALINE_LLM_PROVIDER: ${{ vars.HYALINE_LLM_PROVIDER }}
          HYALINE_LLM_MODEL: ${{ vars.HYALINE_LLM_MODEL }}
          HYALINE_LLM_TOKEN: ${{ secrets.HYALINE_LLM_TOKEN }}