name: Internal - Extract

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository Name'
        type: string
      site:
        description: 'Site Name'
        type: string
      config:
        description: 'Configuration Path'
        type: string
      trigger_merge:
        description: 'Trigger Merge Workflow'
        type: boolean
        default: true
      merge_workflow_ref:
        description: 'Merge Workflow Ref (Branch or Tag). Defaults to default branch.'
        type: string

permissions: {}

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}
      - name: Setup Hyaline CLI
        uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Extract
        uses: ./.github/actions/_extract
        with:
          repo: ${{ inputs.repo }}
          site: ${{ inputs.site }}
          config: ${{ inputs.config }}
          trigger_merge: ${{ inputs.trigger_merge }}
          merge_workflow_ref: ${{ inputs.merge_workflow_ref || github.event.repository.default_branch }}
        env:
          HYALINE_GITHUB_TOKEN: ${{ secrets.HYALINE_GITHUB_TOKEN }}