name: Manual - Extract All

on:
  workflow_dispatch:
    inputs:
      extract_workflow_ref:
        description: 'Extract Workflow Ref (Branch or Tag)'
        type: string
        default: main
        required: true
      trigger_merge:
        description: 'Trigger Merge Workflow'
        type: boolean
        default: true
      merge_workflow_ref:
        description: 'Merge Workflow Ref (Branch or Tag)'
        type: string
        default: main
        required: true

jobs:
  extract-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Hyaline CLI
        uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Extract All
        uses: ./.github/actions/_manual_extract-all
        with:
          extract_workflow_ref: ${{ inputs.extract_workflow_ref }}
          trigger_merge: ${{ inputs.trigger_merge }}
          merge_workflow_ref: ${{ inputs.merge_workflow_ref }}
        env:
          HYALINE_GITHUB_TOKEN: ${{ secrets.HYALINE_GITHUB_TOKEN }}
          HYALINE_CONFIG_GITHUB_TOKEN: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}