name: Extract All

on:
  workflow_dispatch:
    inputs:
      trigger_merge:
        description: 'Trigger Merge Workflow'
        type: boolean
        default: true

permissions: {}

jobs:
  extract-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}
      - name: Setup Hyaline CLI
        uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Extract All
        uses: ./.github/actions/_manual_extract-all
        with:
          extract_workflow_ref: ${{ github.event.repository.default_branch }}
          trigger_merge: ${{ inputs.trigger_merge }}
          merge_workflow_ref: ${{ github.event.repository.default_branch }}
        env:
          HYALINE_CONFIG_GITHUB_TOKEN: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}