name: Internal - Merge

on:
  workflow_dispatch:

concurrency:
  group: _merge
  cancel-in-progress: false

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Hyaline CLI
        uses: appgardenstudios/hyaline-actions/setup@v1
      - name: Merge
        uses: ./.github/actions/_merge
        env:
          HYALINE_GITHUB_TOKEN: ${{ secrets.HYALINE_GITHUB_TOKEN }}