name: Update Hyaline

on:
  workflow_dispatch:

permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYALINE_CONFIG_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Update Hyaline
        uses: ./.github/actions/_update-hyaline
        with:
          upstream: https://github.com/appgardenstudios/hyaline-github-app-config.git