name: Deploy GitHub App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '.github/apps/_hyaline/package-lock.json'
      - name: Install dependencies
        run: npm install
        working-directory: '.github/apps/_hyaline'
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.33.0'
          workingDirectory: 'ags'
          environment: ${{ github.event.inputs.environment }}
          secrets: |
            GITHUB_PRIVATE_KEY
            WEBHOOK_SECRET
            GITHUB_APP_ID
        env:
          GITHUB_PRIVATE_KEY: ${{ secrets.HYALINE_GITHUB_PRIVATE_KEY }}
          WEBHOOK_SECRET: ${{ secrets.HYALINE_GITHUB_APP_WEBHOOK_SECRET }}
          GITHUB_APP_ID: ${{ secrets.HYALINE_GITHUB_APP_ID }}